version: '3.5'

services:
  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      # Change user and password!
      POSTGRES_USER: user
      POSTGRES_PASSWORD: qwerty
      PGDATA: /data/postgres
      POSTGRES_DB: rssaggregator
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped

networks:
  postgres:
    driver: bridge

volumes:
  postgres: